language: node_js
branches:
  only:
    - develop
node_js:
  - node
install:
  - npm install
  - npm run build:dev
script:
  - npm install codecov -g
  # - npm run test
after_success:
  - codecov
# - bash <(curl -s https://codecov.io/bash)